# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'Midterm' do
pod 'AFNetworking'
pod 'GCNetworkReachability'
pod 'RegexKitLite'
end

target 'MidtermTests' do

end

target 'MidtermUITests' do

end

